version: "2.4"
# This server profile used as basis for ping-devop docker-launch

#-------------------------------------------------------------------------------------
#- Ping Identity PingAccess getting started demo
#-
#-     app    console   
#-     443    9000     
#-      |      |      
#-   +----------------+   
#-   |   PingAccess   |   
#-   +----------------+
#-
# Example: Examples below for mounting local directories for inbound server profile and persisting
#          server build.  The local /opt/out directory must be empty when building new server
#             /opt/out - Resulting server build
#             /opt/in  - Inbound server-profile detail in liue of SERVER_PROFILE_URL (must be commented out
#-------------------------------------------------------------------------------------

services:
  pingaccess:
    image: ${PING_IDENTITY_DEVOPS_REGISTRY}/pingaccess:${PING_IDENTITY_DEVOPS_TAG}

    environment:
     - SERVER_PROFILE_URL=https://github.com/hinespj/altusgroup.git
     - SERVER_PROFILE_PATH=server-profile/pingaccess

    env_file:
      - ${HOME}/.pingidentity/devops

    ports:
      - "443:443"
      - "9000:9000"

    networks:
      - pingnet

    volumes:
      - ${HOME}/projects/devops/volumes/pingaccess-out:/opt/out
      # - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingaccess:/opt/in

networks:
  pingnet:

volumes:
  pingaccess-out: